Move script to GH Action step

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -28,8 +28,18 @@ jobs:
       - name: Build project
         run: ./gradlew assemble
 
-      - name: Verify output
-        run: ../scripts/test_program.sh build/libs/joke-app.jar
+      - name: Verify program
+        run: |
+          OUTPUT=$(./gradlew run)
+          echo "$OUTPUT"
+  
+          if echo "$OUTPUT" | grep -q "Here goes the joke:"; then
+            echo "Assertion passed, program compiled correctly"
+            exit 0
+          else
+            echo "Assertion failed"
+            exit 1
+          fi
 
       - name: Test project
         run: ./gradlew test
